server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///cs?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql123

  jpa:
    show-sql: true

    #jsp设置
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp


